from matplotlib import pyplot as plt
import numpy as np

# fig, a = plt.subplots(2, 2)
# x = np.arange(1, 5)
# a[0][0].plot(x, x * x, color='g')
# a[0][0].ylabel('Square')
# a[0][0].xlabel('Num')
# a[0][0].set_title('sqaure')
# a[0][1].plot(x, np.sqrt(x), color='r')
# a[0][1].set_title('sqaure root')
# a[1][0].plot(x, np.exp(x), color='c')
# a[1][0].set_title('exp')
# a[1][1].plot(x, np.log10(x), color='b')
# a[1][1].set_title('log')
# plt.show()

fig, a = plt.subplots(2, 2)
x = np.arange(1, 5)
a[0][0].plot(x, x * x, color='g')
a[0][0].ylabel('Square')
a[0][0].xlabel('Num')
a[0][0].set_title('sqaure')
a[0][1].plot(x, np.sqrt(x), color='r')
a[0][1].set_title('sqaure root')
a[1][0].plot(x, np.exp(x), color='c')
a[1][0].set_title('exp')
a[1][1].plot(x, np.log10(x), color='b')
a[1][1].set_title('log')
plt.show()
